### ISSUE TITLE
Python3 SMTP ValueError: server_hostname cannot be an empty string or start with a leading dot

### ISSUE THREAD

**Issue by ebcoelho** [BennyE/stellar-dynpsk#2]
Issue running the script after python upgrade from 3.5 to 3.7.

Found some references on link below:
https://github.com/ansible/ansible/pull/44552#issue-210314052

$ python3 stellar-dynpsk.py 

Stellar DynPSK - a simple PSK changer for Stellar Wireless SSIDs
Written by Benny Eggerstedt in 2018
This is free software not provided/shipped by Alcatel-Lucent Enterprise. Use it at your own risk!

[+] Reading settings.json file
[!] Ignoring certificate warnings or self-signed certificates!
[!] You should really fix this!
[*] Attempting to connect to OmniVista server @ https://ov2500.lettel.com.br
[*] Connection to ov2500.lettel.com.br successful!
[*] Working on AP GROUP L2GRE-STELLAR...
    [*] Found instanceID 5b57933ce4b0a167146a7b78 for AP group L2GRE-STELLAR
    [*] Found deviceId 5b5869a4e4b0391cd6b2a3f6 for SSID ALCA-PSK
    [+] Changed the PSK of AP GROUP L2GRE-STELLAR, SSID ALCA-PSK to: aazdbWHk
Traceback (most recent call last):
  File "stellar-dynpsk.py", line 660, in <module>
    smtp_server, smtp_auth, smtp_user, smtp_port, smtp_password)
  File "stellar-dynpsk.py", line 454, in send_mail
    smtp.starttls()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 771, in starttls
    server_hostname=self._host)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 843, in _create
    owner=self, session=self._session,
ValueError: server_hostname cannot be an empty string or start with a leading dot.

**Comment by BennyE** [comment]
Thanks, I'll look into it this evening.

**Comment by BennyE** [comment]
Hi, can you give this a try? (I created a separate branch to try/verify the potential fix, before merging this.)
https://github.com/BennyE/stellar-dynpsk/blob/smtpfix/stellar-dynpsk.py

**Comment by ebcoelho** [comment]
the new version worked fine with python 3.7.0, thanks for the fix!

> 
>
>Eduardo:stellar-dynpsk eduardo$ python3 stellar-dynpsk.py 
>
>Stellar DynPSK - a simple PSK changer for Stellar Wireless SSIDs
>Written by Benny Eggerstedt in 2018
>This is free software not provided/shipped by Alcatel-Lucent Enterprise. Use it at your own risk!
>
> Reading settings.json file
> Ignoring certificate warnings or self-signed certificates!
>You should really fix this!
>Attempting to connect to OmniVista server @ https://ov2500.domain.com
>Connection to ov2500.domain.com successful!
>Working on AP GROUP STELLAR...
>    Found instanceID 5b57933ce4b0a167146a7b78 for AP group STELLAR
>    Found deviceId 5b5869a4e4b0391cd6b2a3f6 for SSID ALCA-PSK
>    Changed the PSK of AP GROUP STELLAR, SSID ALCA-PSK to: ahYRVeaG
>    Scan the QR Code sent via mail with your mobile phone and login to the network!

**Comment by BennyE** [comment]
Thanks for testing this Eduardo, much appreciated. I merged the fix to master and will delete the smtpfix branch.
